name: xarray-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.5
  - numpy
  - pandas
  - numpydoc
  - matplotlib
  - seaborn
  - dask
  - ipython
  - sphinx
  - netCDF4
  - hdf4  # temporary install to get netCD4 working (GH1106)
  - cartopy
